---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: default
spec:
  storageClassName: default
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: fast
spec:
  storageClassName: fast
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: backup
spec:
  storageClassName: backup
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bigdata
spec:
  storageClassName: bigdata
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
