#
# K8s 관리자가 생성
#
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-jenkins
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s-sigs.io/nfs-subdir-external-provisioner # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-jenkins
spec:
  storageClassName: sc-jenkins
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---