apiVersion: graphcore.ai/v1alpha1
kind: IPUJob
metadata:
  name: interactive-sample-job-mnist-02
spec:
  #modelReplicas: "4"
  #ipusPerModelReplica: "1"
  jobInstances: 1
  ipusPerJobInstance: "1"
  #workersPerJobInstance: ""
  #modelReplicasPerWorker: ""
  #restartPolicy: OnFailure #Restart policy for the job. One of: Always, OnFailure, Never and ExitCode. Defaults to Never.
  #cleanPodPolicy: "All" #Clean pod policy for the job after it is finished. One of: None, All, Workers Defaults to None.
  interactive:
    ttl: 36000 # how long should the interactive session last, TTL specifies how long this ipujob should live
  workers:
    replicas: 1
    template:
      metadata:
        labels:
          app: interactive-sample-job-mnist-launcher-02
      spec:
        containers: 
        - name: mnist-02
          # TODO: replace this with a publicly accessible image
          image:  docker.io/mkbahk/gc-amd-p22-tf24-k8s-integration:1.3
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          env: 
          - name: "IPUOF_LOG_LEVEL"
            value: "INFO" 
          - name: "POPLAR_LOG_LEVEL"
            value: "INFO"     
