apiVersion: graphcore.ai/v1alpha1
kind: IPUJob
metadata:
  name: mnist-interactive-sample-job-10
spec:
  #modelReplicas: "4"
  #ipusPerModelReplica: "1"
  jobInstances: 1
  ipusPerJobInstance: "1"
  interactive:
    ttl: 36000 # how long should the interactive session last
  workers:
    replicas: 1
    template:
      metadata:
        labels:
          app: mnist-interactive-launcher-01 
      spec:
        containers: 
        - name: mnist-01
          # TODO: replace this with a publicly accessible image
          image: docker.io/mkbahk/gc-amd-p22-tf24-k8s-integration:1.3
          imagePullPolicy: IfNotPresent
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
          env: 
          - name: "IPUOF_LOG_LEVEL"
            value: "INFO" 
          - name: "POPLAR_LOG_LEVEL"
            value: "INFO"     
