apiVersion: graphcore.ai/v1alpha1
kind: IPUJob
metadata:
  name: interactive-sample-job
spec:
  #modelReplicas: "4"
  #ipusPerModelReplica: "1"
  jobInstances: 1
  ipusPerJobInstance: "1"
  interactive:
    ttl: 3600 # how long should the interactive session last
  workers:
    replicas: 1
    template:
      metadata:
        labels:
          app: resnet-launcher 
      spec:
        containers:
        - name: resnet
          # TODO: replace this with a publicly accessible image
          image: docker.io/mkbahk/resnet-poplar-2.1:v1.0.1
          imagePullPolicy: Always
          env: 
          - name: "IPUOF_LOG_LEVEL"
            value: "INFO" 
          - name: "POPLAR_LOG_LEVEL"
            value: "INFO"     
