apiVersion: graphcore.ai/v1alpha1
kind: IPUJob
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"graphcore.ai/v1alpha1","kind":"IPUJob","metadata":{"annotations":{},"name":"ipujob-sample2","namespace":"default"},"spec":{"ipusPerJobInstance":"1","jobInstances":1,"launcher":{"command":["mpirun","--allow-run-as-root","--bind-to","none","-np","1","python3","/public_examples/applications/tensorflow/cnns/training/train.py","--dataset=cifar-10","--synthetic-data","--model-size=8","--batch-size=1","--batches-per-step=10","--gradient-accumulation-count=10","--no-validation","--no-stochastic-rounding","--iterations=20"]},"workers":{"replicas":1,"template":{"metadata":{"labels":{"app":"resnet-launcher"}},"spec":{"containers":[{"env":[{"name":"IPUOF_LOG_LEVEL","value":"INFO"},{"name":"POPLAR_LOG_LEVEL","value":"INFO"}],"image":"mkbahk/resnet-poplar-2.0:latest","name":"resnet"}]}}}}}
  creationTimestamp: "2021-10-27T09:27:52Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2021-10-27T09:41:16Z"
  finalizers:
  - ipu.finalizers.graphcore.ai
  generation: 7
  managedFields:
  - apiVersion: graphcore.ai/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers: {}
      f:status:
        .: {}
        f:iPUPartitionCreated: {}
        f:launcherStatus: {}
        f:restartCount: {}
    manager: manager
    operation: Update
    time: "2021-10-27T09:27:52Z"
  - apiVersion: graphcore.ai/v1alpha1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        .: {}
        f:ipusPerJobInstance: {}
        f:ipusPerModelReplica: {}
        f:jobInstances: {}
        f:launcher:
          .: {}
          f:command: {}
        f:modelReplicas: {}
        f:workers:
          .: {}
          f:replicas: {}
          f:template:
            .: {}
            f:metadata: {}
            f:spec:
              .: {}
              f:containers: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-10-29T01:23:49Z"
  name: ipujob-sample2
  namespace: default
  resourceVersion: "666049"
  uid: 47e31e24-9a27-4259-b336-1cffebe9d828
spec:
  cleanPodPolicy: None
  ipusPerJobInstance: "1"
  jobInstances: 1
  launcher:
    command:
    - mpirun
    - --allow-run-as-root
    - --bind-to
    - none
    - -np
    - "1"
    - python3
    - /public_examples/applications/tensorflow/cnns/training/train.py
    - --dataset=cifar-10
    - --synthetic-data
    - --model-size=8
    - --batch-size=1
    - --batches-per-step=10
    - --gradient-accumulation-count=10
    - --no-validation
    - --no-stochastic-rounding
    - --iterations=20
  modelReplicasPerWorker: "1"
  restartPolicy:
    backOffLimit: 3
    type: Never
  workers:
    replicas: 1
    template:
      metadata: {}
      spec:
        containers:
        - env:
          - name: IPUOF_LOG_LEVEL
            value: INFO
          - name: POPLAR_LOG_LEVEL
            value: INFO
          image: mkbahk/resnet-poplar-2.0:latest
          name: resnet
          resources: {}
  workersPerJobInstance: "1"
