---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-request-pvc-pod
spec:
  containers:
  - image: nginx:latest
    name: nginx-container
    volumeMounts:
    - name: htmldata
      mountPath: /usr/share/nginx/html
  volumes:
  - name: htmldata
    persistentVolumeClaim:
      claimName: pvc-slow-1
---