---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-hostpath
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /tmp/pv-hostpath
---