---
apiVersion: v1
kind: Pod
metadata:
  name: annotations-demo-pod
  annotations:
    builder: "Moon-Kee Bahk(mkbahk@megazone.com)"
    buildDate: "2022-06-20"
    imageregistry: "https://dockerhub.com/"
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
---