---
apiVersion: v1
kind: Pod
metadata:
  name: nginxweb-pod-1-21-0
  labels:
    app: "nginxweb"
    version: "1.21.0"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21.0
    ports:
    - containerPort: 80
---
