---
apiVersion: batch/v1
kind: Job
metadata:
  name: ubuntu-batch-job
spec:
  #competions: 5
  #parallelism: 2
  #activeDeadlineSeconds: 5
  template:
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:18.04
        command: ["bash"]
        args:
        - "-c"
        - "echo 'Hello Ubuntu, going to sleep 30 Sec.'; sleep 30; echo 'Job Done.'"
      #restartPolicy: Never
      restartPolicy: OnFailure
  backoffLimit: 3
---