---
apiVersion: v1
kind: Pod
metadata:
  name: kongweb-main-pod
  labels:
    "app": "kongweb-main"
  namespace: kong
spec:
  hostname: kongweb-main-pod
  subdomain: kongweb-main-svc
  containers:
  - name: kongweb-main-container
    image: mkbahk/kongnginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kongweb-main-svc
  #서비스 이름은 자동적으로 kongweb-svc.default.svc.cluster.local로 등록됨
  namespace: kong
spec:
  selector:
    "app": "kongweb-main"
  ports:
  - protocol: TCP
    port: 8787
    targetPort: 80
---