---
apiVersion: v1
kind: Pod
metadata:
  name: kongweb-sub1-sub1-pod
  labels:
    "app": "kongweb-sub1-sub1"
  namespace: ingress-nginx
spec:
  hostname: kongweb-sub1-sub1-pod
  subdomain: kongweb-sub1-sub1-svc
  containers:
  - name: kongweb-sub1-sub1-container
    image: mkbahk/kongnginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kongweb-sub1-sub1-svc
  #서비스 이름은 자동적으로 kongweb-svc.default.svc.cluster.local로 등록됨
  namespace: ingress-nginx
spec:
  selector:
    "app": "kongweb-sub1-sub1"
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---