---
apiVersion: v1
kind: Pod
metadata:
  name: node-label-pod
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80
  nodeSelector:
    #조건이 2개 이상이면 AND 조건, true, false, yes, no는 반드시 ""로 묶여야 함
    accelerator: "nvidia-a100"
    disk: "ssd"
---


