---
apiVersion: v1
kind: Pod
metadata:
  name: multi-nginx-nodejs-pod
spec:
  containers:
  - name: nginx80container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
  - name: hellonodejs7777container
    image: mkbahk/hellonodejs:1.0
    ports:
    - containerPort: 7777
      protocol: TCP
---
