---
apiVersion: v1
kind: Pod
metadata:
  name: multi-nginx-ubuntu-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
  - name: ubuntu-container
    image: ubuntu:18.04
    command:
    - sleep
    - "10000"
---
