---
apiVersion: v1
kind: Pod
metadata:
  name: nginxweb-simple-pod
  labels:
    "app": "nginxweb"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
---
