---
apiVersion: v1
kind: Pod
metadata:
  name: nginxweb-pod
  labels:
    "app": "nginxweb"
spec:
  #
  hostname: nginx1210
  subdomain: nginxweb-svc
  #호스트 이름과 서브도메인이 K8s svc의 이름과 같은 경우로 지정된면 CoreDNS에 nginx2120.nginxweb-svc.default.svc.cluster.local 로 등록된다.
  containers:
  - name: nginx-container
    image: mkbahk/nginx:1.21.0
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxweb-svc
spec:
  selector:
    "app": "nginxweb"
  ports:
  - protocol: TCP
    port: 8780
    targetPort: 80
  type: LoadBalancer
---