apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginxweb
  name: nginxweb
spec:
  containers:
  - image: nginx:latest
    name: nginxweb
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
