---
apiVersion: apps/v1
#kind: ReplicaSet
kind: Deployment
metadata:
  name: nginx-v121stable-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nginxweb"
      version: "v121stable"
  template:
    metadata:
      name: nginxweb-v121stable-pod
      labels:
        app: "nginxweb"
        version: "v121stable"
    spec:
      containers:
      - name: nginx-container-121
        image: nginx:1.21
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
#kind: ReplicaSet
kind: Deployment
metadata:
  name: nginx-v122alpha-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "nginxweb"
      version: "v122alpha"
  template:
    metadata:
      name: nginxweb-v122alpha-pod
      labels:
        app: "nginxweb"
        version: "v122alpha"
    spec:
      containers:
      - name: nginx-container-122
        image: nginx:1.22
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginxweb-svc
spec:
  selector:
    app: "nginxweb"
  ports:
  - protocol: TCP
    port: 8880
    targetPort: 80
  type: LoadBalancer
---
#LB공인IP->Server:8880 -> Deployment -> ReplicaSet->POD:80->Container:nginx:1.21:80 
---