---
apiVersion: v1
kind: Pod
metadata:
  name: nginxweb-dns-pod
  labels:
    "app": "nginxweb"
spec:
  containers:
  - name: nginx-container
    image: nginx:1.21
    ports:
    - containerPort: 80
  dnsPolicy: "None"
  dnsConfig:
    nameservers:
    - 8.8.8.8
    - 8.8.4.4
    searches:
    - ns1.megazone.com
    options:
    - name: ndots
      value: "2"
      name: edns0
---
apiVersion: v1
kind: Service
metadata:
  name: nginxweb-dns-svc
spec:
  selector:
    "app": "nginxweb"
  ports:
  - protocol: TCP
    port: 8680
    targetPort: 80
  type: LoadBalancer
---