---
apiVersion: v1
kind: Pod
metadata:
  name: nginxweb-simple-pod
  labels:
    "app": "nginxweb"
spec:
  #hostname: nginx1210
  #subdomain: hellosub
  containers:
  - name: nginx-container
    image: mkbahk/nginx:1.21.0
    ports:
    - containerPort: 80
---
