---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-replication-controller
spec:
  replicas: 5
  selector:
    app: nginxweb
  template:
    metadata:
      name: nginxweb-pod
      labels:
        app: nginxweb
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.22
        ports:
        - containerPort: 80
---
