---
apiVersion: v1
kind: Pod
metadata:
  name: headless-1210-pod
  labels:
    "app": "headless"
spec:
  #
  hostname: nginx1210
  subdomain: headless-svc
  #
  containers:
  - name: nginx-container
    image: mkbahk/nginx:1.21.0
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: headless-1220-pod
  labels:
    "app": "headless"
spec:
  #
  hostname: nginx1220
  subdomain: headless-svc
  #
  containers:
  - name: nginx-container
    image: mkbahk/nginx:1.22.0
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  selector:
    "app": "headless"
  #
  clusterIP: None
  #
  ports:
  - protocol: TCP
    port: 8780
    targetPort: 80
---
#nslookup nginx1220.headless-svc