---
apiVersion: v1
kind: Pod
metadata:
  name: resource-nginx-pod
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      requests:
        cpu: 256
        memory: 256Mi
      limits:
        cpu: 512
        memory: 5120Mi
---
