---
apiVersion: v1
kind: Pod
metadata:
  name: storage-emptydir-pod
  labels:
    environment: production
    app: nginx
spec:
  containers:
  - name: nginx-container-1
    image: nginx:1.14.2
    ports:
    - containerPort: 80
    volumeMounts:
    - name: cache-volume
      mountPath: /usr/share/nginx/html
  - name: nginx-container-2
    image: mkbahk/ubuntu-genhtml:latest
    volumeMounts:
    - name: cache-volume
      mountPath: /usr/share/nginx/html
  nodeSelector:
    kubernetes.io/hostname: pod642
  volumes:
    - name: cache-volume
      emptyDir: {}
---